name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Check for snapshot differences
      run: |
        if [[ -n $(git status --porcelain tests/fixtures/snapshots) ]]; then
          echo "Error: Snapshot tests generated differences"
          git diff tests/fixtures/snapshots
          exit 1
        fi

    - name: Upload test coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-coverage-${{ matrix.node-version }}
        path: coverage/
        retention-days: 30